spring.application.name: admin-server

server.port: 8090

spring.boot.admin.url: http://localhost:${server.port}

eureka.instance.leaseRenewalIntervalInSeconds: 10
eureka.instance.leaseExpirationDurationInSeconds: 30
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management.security.enabled: false  # 关闭actuator安全认证